### PR TITLE
Remove created resource

### PR DESCRIPTION
**Pull request by martinsrenan**

### CODE REVIEW

**Comment by martinsrenan** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
In Terraform Init and Plan


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_instance.web2 will be destroyed
  # (because aws_instance.web2 is not in configuration)
- resource "aws_instance" "web2" {
      - ami                                  = "ami-000722651477bd39b" -> null
      - arn                                  = "arn:aws:ec2:us-east-1:856602439332:instance/i-01b7559b085701cd8" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "us-east-1c" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 1 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-01b7559b085701cd8" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t2.micro" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-020b4c1bd1a4c0321" -> null
      - private_dns                          = "ip-172-31-4-248.ec2.internal" -> null
      - private_ip                           = "172.31.4.248" -> null
      - public_dns                           = "ec2-34-237-124-191.compute-1.amazonaws.com" -> null
      - public_ip                            = "34.237.124.191" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0e0b2ddfbd4fd9aba" -> null
      - tags                                 = {
          - "Name" = "atlantis-terraform-teste2"
        } -> null
      - tags_all                             = {
          - "Name" = "atlantis-terraform-teste2"
        } -> null
      - tenancy                              = "default" -> null
      - user_data_replace_on_change          = false -> null
      - vpc_security_group_ids               = [
          - "sg-0afc42fadaf8ccc63",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "standard" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-03987d0ee41b781ec" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=martinsrenan%252FRepo1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by anacarolmbaia — APPROVED** [review]

**Comment by martinsrenan** [comment]
atlantis apply

**Comment by martinsrenan** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
In Terraform Apply

aws_instance.web2: Destroying... [id=i-01b7559b085701cd8]
aws_instance.web2: Still destroying... [id=i-01b7559b085701cd8, 10s elapsed]
aws_instance.web2: Still destroying... [id=i-01b7559b085701cd8, 20s elapsed]
aws_instance.web2: Destruction complete after 30s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.


```

**Comment by martinsrenan** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by martinsrenan** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
