### PR TITLE
Teste8

### PR DESCRIPTION
**Pull request by martinsrenan**

### CODE REVIEW

**Comment by martinsrenan** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.teste4 will be created
+ resource "null_resource" "teste4" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.solfacil.com.br/lock?id=martinsrenan%252FRepo1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by martinsrenan** [comment]
atlantis apply

**Comment by martinsrenan** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Review by anacarolmbaia — APPROVED** [review]

**Comment by martinsrenan** [comment]
atlantis plan

**Comment by martinsrenan** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.teste4 will be created
+ resource "null_resource" "teste4" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.solfacil.com.br/lock?id=martinsrenan%252FRepo1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by martinsrenan** [comment]
**Warning**: The plan for dir: `.` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Pull request closed without merging**
